//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinpeMovilWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bancos
    {
        public string CodBanco { get; set; }
        public string NombreBanco { get; set; }
        public bool ActivaPrincipal { get; set; }
        public string TelefonoSinpe { get; set; }
    }
}
