//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinpeMovilWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraGeneral
    {
        public int IdBitacora { get; set; }
        public string CodComercio { get; set; }
        public short TipoBitacora { get; set; }
        public string IP { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
