//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinpeMovilWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacoraPagos
    {
        public int id { get; set; }
        public string CodComercio { get; set; }
        public System.DateTime FechaHora { get; set; }
        public string CodBanco { get; set; }
        public decimal MontoPago { get; set; }
        public string Telefono { get; set; }
        public string Ip { get; set; }
    }
}
