//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinpeMovilWA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comercios
    {
        public string CodComercio { get; set; }
        public string NombreComercio { get; set; }
        public string NombreEncargado { get; set; }
        public string Telefono { get; set; }
        public string TelefonoSinpe { get; set; }
        public string Email { get; set; }
        public string Provincia { get; set; }
        public string Canton { get; set; }
        public string Distrito { get; set; }
        public Nullable<int> CantidadVisitas { get; set; }
        public string Logo { get; set; }
        public string TipoPlan { get; set; }
        public Nullable<bool> FacturaElectronica { get; set; }
        public string TipoCedula { get; set; }
        public string NumeroCedula { get; set; }
        public string RazonSocial { get; set; }
        public string CorreoFE { get; set; }
        public Nullable<System.DateTime> FechaVence { get; set; }
        public string CodVendedor { get; set; }
        public Nullable<short> TipoComercio { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    }
}
