//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinpeMovilWA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SinpeMovilPruebasEntities : DbContext
    {
        public SinpeMovilPruebasEntities()
            : base("name=SinpeMovilPruebasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bancos> Bancos { get; set; }
        public virtual DbSet<BitacoraGeneral> BitacoraGeneral { get; set; }
        public virtual DbSet<BitacoraIngreso> BitacoraIngreso { get; set; }
        public virtual DbSet<BitacoraPagos> BitacoraPagos { get; set; }
        public virtual DbSet<Comercios> Comercios { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vendedores> Vendedores { get; set; }
    }
}
